---

- name: list out files in directory
  hosts: all
  vars:
    directory: $HOME

  tasks:

    - command: "ls {{directory}}"
      register: dir_out

    - debug: var={{item}}
      with_items: dir_out.stdout_lines
