---
- name: Restart vociwebapi
  hosts: nc01
  become: true
  tasks:

  - name: restart vociwebapi
    ansible.builtin.service:
      name: vociwebapi
      state: restarted
      enabled: true

  - name: is port 17171 running?
    command: tail /var/log/vociwebapi/err.log
    register: tail
  - debug:
      msg: "{{ tail.stdout_lines }}"

   
...
