---
- name: Show Logs
  hosts: Vocis
  become: true
  tasks:

  - name: is port 17171 running?
    command: tail /var/log/vociwebapi/err.log
    register: tail
  - debug:
      msg: "{{ tail.stdout_lines }}"

  - name: is port 17170 running?
    command: tail /var/log/vociserver/err.log
    register: tail
  - debug:
      msg: "{{ tail.stdout_lines }}"
...
